version: 2.1

orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@1.5.0
  aws-ecr: circleci/aws-ecr@7.2.0
workflows:
  node-react-builds:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - build
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 10m
          region: AWS_REGION
          repo: 'pm-react'
          skip-when-tags-exist: false
          tag: '${CIRCLE_BRANCH}-latest'
jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run: npm install
      - run: CI=false npm run build

